FROM public.ecr.aws/lambda/python:3.11

# Copy requirements-lambda and install
COPY requirements-lambda.txt ${LAMBDA_TASK_ROOT}
RUN pip install --no-cache-dir -r requirements-lambda.txt

# Copy logic and handler
COPY lambda_function.py ${LAMBDA_TASK_ROOT}
COPY rag_logic.py ${LAMBDA_TASK_ROOT}
COPY prompts.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler function
CMD [ "lambda_function.lambda_handler" ]